---

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
    notify: update timezone

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Install NTP
      apt: package=ntp,ntpdate state=present update_cache=yes
      tags: ntp
      notify:
        - restart ntp
        - force ntp update
      tags: ntp

- name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp

  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
  
    #- name: force ntp update
     # shell: "service ntp stop && ntpdate -s {{ hostvars[groups[timelord][0]]['ansible_' ~ ntp_netdevice]['ipv4']['address'] }} && service ntp start"
     # when: ansible_hostname != timelord

  

    




